# Generated by Django 3.1.1 on 2020-09-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flourish_maternal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubjectscreening',
            name='screening_identifier',
            field=models.CharField(db_index=True, max_length=36, verbose_name='Eligibility Identifier'),
        ),
        migrations.AlterField(
            model_name='subjectscreening',
            name='screening_identifier',
            field=models.CharField(max_length=36, unique=True, verbose_name='Eligibility Identifier'),
        ),
    ]
